// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One `alias → pass index` binding in [`PipelineMetadata::aliases`].
 */
export type AliasBinding = { 
/**
 * The pass's semantic alias (`aliasN` / `#pragma name`).
 */
alias: string, 
/**
 * Index of the pass it names, into [`Project::passes`].
 */
passIndex: number, };
