// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortDirection } from "./PortDirection";
import type { PortType } from "./PortType";

/**
 * One typed port the collapsed subgraph node exposes to the exterior, bound to
 * a single interior endpoint (Phase 6, #56).
 *
 * A boundary port is the bridge between the subgraph's *outside* (an edge on the
 * collapsed `kind == "subgraph"` [`Node`]) and its *inside* (a port on one
 * interior [`Node`]):
 *
 * - An [`PortDirection::In`] port **feeds an interior input port**: an exterior
 *   edge connects into it, and the value flows to `(interior_node,
 *   interior_port)` inside.
 * - An [`PortDirection::Out`] port **carries an interior output port to the
 *   exterior**: it surfaces the value produced at `(interior_node,
 *   interior_port)` so exterior edges can read it.
 */
export type BoundaryPort = { 
/**
 * The port name exposed on the collapsed subgraph node (what exterior edges
 * connect to). Stable across [`LibraryItem::instantiate`] — it is a port
 * name, not an id.
 */
name: string, 
/**
 * The typed value flowing through this port. Reuses the frozen IR
 * [`PortType`] so boundary ports type-check identically to interior ports.
 */
ty: PortType, 
/**
 * Whether this port is an exterior **input** (feeds an interior input) or an
 * exterior **output** (carries an interior output out).
 */
direction: PortDirection, 
/**
 * The id of the interior [`Node`] this boundary maps to. **Rewritten** by
 * [`LibraryItem::instantiate`] through the old→new node-id map.
 */
interiorNode: string, 
/**
 * The port name on `interior_node` this boundary maps to. Stable across
 * instantiation — it is a port name, not an id.
 */
interiorPort: string, };
