// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A reserved RetroArch builtin-semantic uniform a [`NodeOp::Builtin`] reads
 * (Spec §8.1; the worked-example header). These names are **reserved** — the
 * emitter spells each exactly as the RetroArch slang identifier (e.g.
 * `SourceSize`, `FrameCount`, `MVP`), reading them from the push-constant /
 * global UBO. Each variant's documented [`PortType`] is its value type, which
 * the type checker uses for the builtin node's output port.
 */
export type BuiltinSemantic = "sourceSize" | "originalSize" | "outputSize" | "finalViewportSize" | "frameCount" | "frameDirection" | "mvp";
