// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Diagnostics } from "./Diagnostics";

/**
 * The result of compiling a typed [`IrGraph`] to slang — the payload the
 * `compile_graph` IPC command (#42) returns to the webview.
 *
 * It bundles the two things the Phase-5 editor's debounced edit loop needs after
 * every graph change: the [`Diagnostics`] to surface inline (always present —
 * empty when the graph is clean) and the emitted slang `source` (present only
 * when the graph type-checked clean and lowered + emitted successfully, `None`
 * otherwise). A caller renders the diagnostics regardless, and previews/compiles
 * the `source` only when it is `Some`.
 *
 * `serde` + `#[ts(export)]` so it round-trips over IPC as a single typed shape.
 */
export type CompileGraphResult = { 
/**
 * The emitted `.slang` source, or `None` when the graph had blocking errors
 * (and so was never lowered/emitted).
 */
source: string | null, 
/**
 * The type-checker diagnostics (empty when the graph is fully clean). Always
 * present so the editor can render them whether or not `source` was produced.
 */
diagnostics: Diagnostics, };
