// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A typed literal value produced by a [`NodeOp::Const`] (Spec §8.2). Each
 * variant pins both the value and its [`PortType`] — the type checker (#40)
 * reads [`const_type`](ConstValue::port_type) for the const node's output port,
 * and the emitter (#42) writes the matching slang literal/constructor.
 */
export type ConstValue = { "kind": "float", 
/**
 * The scalar value.
 */
value: number, } | { "kind": "vec2", 
/**
 * The two components `[x, y]`.
 */
value: [number, number], } | { "kind": "vec3", 
/**
 * The three components `[x, y, z]`.
 */
value: [number, number, number], } | { "kind": "vec4", 
/**
 * The four components `[x, y, z, w]`.
 */
value: [number, number, number, number], } | { "kind": "int", 
/**
 * The integer value.
 */
value: number, } | { "kind": "bool", 
/**
 * The boolean value.
 */
value: boolean, };
