// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticSeverity } from "./DiagnosticSeverity";

/**
 * A single structured diagnostic produced when type-checking an [`IrGraph`]
 * (#40). Every diagnostic carries the **offending node id** (and, where it
 * applies, the offending **port id** on that node) so the Phase-5 editor can map
 * it to an inline highlight on the exact node/port. It is `serde` +
 * `#[ts(export)]` because the future `compile_graph` IPC command returns these
 * to the webview (module doc §A).
 *
 * The `code` is a short stable machine-readable tag (e.g. `"typeMismatch"`,
 * `"cycle"`, `"missingOutput"`) the UI can switch on without parsing `message`;
 * `message` is the human-readable explanation.
 */
export type Diagnostic = { 
/**
 * Whether this blocks lowering ([`Error`](DiagnosticSeverity::Error)) or is
 * advisory ([`Warning`](DiagnosticSeverity::Warning)).
 */
severity: DiagnosticSeverity, 
/**
 * A short, stable, machine-readable category tag (e.g. `"typeMismatch"`).
 */
code: string, 
/**
 * The human-readable explanation of the problem.
 */
message: string, 
/**
 * The id of the offending [`IrNode`] — always present so the editor can map
 * the diagnostic to a node.
 */
node: string, 
/**
 * The offending port name on [`node`](Diagnostic::node), when the diagnostic
 * is about a specific port (e.g. a type mismatch on an input port); `None`
 * for node-level problems (e.g. a cycle, an unknown parameter).
 *
 * Plain `#[serde(default)]` (no `skip_serializing_if`): ts-rs cannot parse
 * `skip_serializing_if` and would emit a required `port: string | null`
 * binding while the wire payload omitted the key — a mismatch. Always
 * serializing `null` when `None` keeps the wire shape and the generated TS
 * type identical (matching the [`crate::PassSource::WholePassCode`]
 * `filename` precedent).
 */
port: string | null, };
