// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The severity of a [`Diagnostic`] emitted by the type checker (#40).
 *
 * An [`Error`](DiagnosticSeverity::Error) means the graph is **not** lowerable /
 * emittable (it would produce invalid slang or has no defined meaning); a
 * [`Warning`](DiagnosticSeverity::Warning) is advisory and does not block
 * lowering. [`Diagnostics::has_errors`] keys off this distinction so callers
 * (lowering #41, `compile_graph` #42) can cleanly tell "clean" from "broken".
 */
export type DiagnosticSeverity = "error" | "warning";
