// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Diagnostic } from "./Diagnostic";

/**
 * The result of type-checking an [`IrGraph`] (#40): the ordered list of
 * [`Diagnostic`]s found. A clean graph yields an empty collection.
 *
 * This is the value lowering (#41) and the `compile_graph` command (#42) consume
 * to decide whether to proceed: [`has_errors`](Diagnostics::has_errors)
 * distinguishes "clean" (lowerable) from "has blocking errors" cleanly, without
 * the caller re-scanning severities. It is `serde` + `#[ts(export)]` so the
 * whole collection round-trips over IPC to the editor.
 */
export type Diagnostics = { 
/**
 * The diagnostics found, in the order the checker emitted them.
 */
items: Array<Diagnostic>, };
