// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A directed connection between two node ports (Architecture §C, Spec §8.2).
 */
export type Edge = { 
/**
 * Stable unique id for this connection.
 */
id: string, 
/**
 * Id of the node the connection starts at.
 */
source: string, 
/**
 * Output port on the source node.
 */
sourcePort: string, 
/**
 * Id of the node the connection ends at.
 */
target: string, 
/**
 * Input port on the target node.
 */
targetPort: string, };
