// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Severity of an [`EngineErrorEvent`] (#62): does it stop rendering, or is it a
 * transient/advisory problem the app can keep running through?
 *
 * An [`Error`](EngineSeverity::Error) means this frame/pass failed (a slang
 * compile error, an FBO allocation failure); a [`Warning`](EngineSeverity::Warning)
 * is advisory. Mirrors [`crate::ir::DiagnosticSeverity`] but is a distinct type
 * because engine events also carry the engine-specific [`EngineStatus`].
 */
export type EngineSeverity = "error" | "warning";
