// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EngineSeverity } from "./EngineSeverity";

/**
 * A structured render/engine error surfaced from the render thread (#62).
 *
 * Produced when the renderer cannot produce a fresh frame: a slang/glslang
 * compile failure for an in-memory chain pass (mapped to its owning pass), an
 * FBO/device allocation failure, or a device-lost. The frontend synthesizes a
 * diagnostic into its problems list (pass/node tagged when `pass_id`/`node_id`
 * are present) and shows a non-blocking toast for transient cases.
 *
 * `code` is a short stable machine-readable tag (`"slangCompile"`,
 * `"deviceLost"`, `"fboAlloc"`, `"readback"`); `message` is human-readable.
 */
export type EngineErrorEvent = { 
/**
 * Whether this stops the affected pass/frame or is advisory.
 */
severity: EngineSeverity, 
/**
 * A short, stable, machine-readable category tag (e.g. `"slangCompile"`).
 */
code: string, 
/**
 * The human-readable explanation of the problem.
 */
message: string, 
/**
 * The pipeline pass id this error is about, when it maps to one (e.g. a
 * whole-pass slang compile failure). `None` for pipeline-wide failures.
 *
 * Always serialized (`null` when `None`) so the wire shape and the generated
 * TS type stay identical (the [`crate::ir::Diagnostic::port`] precedent).
 */
passId: string | null, 
/**
 * The offending editor node id, when the error maps to one. `None` for
 * pass-level or pipeline-wide failures.
 */
nodeId: string | null, };
