// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The render engine's liveness state (#62), surfaced to the preview pane so the
 * user can tell a fresh render from a held last-good frame from a stopped engine.
 *
 * `render_into` already emits a "waiting"/last-good frame on a not-ready/error
 * frame (the engine never tears down on a bad chain) — this names that state so
 * the preview can badge it instead of silently showing stale pixels.
 */
export type EngineStatus = "live" | "lastGood" | "stopped";
