// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EngineErrorEvent } from "./EngineErrorEvent";
import type { EngineStatus } from "./EngineStatus";

/**
 * A status/error event from the render thread to the frontend (#62), carried over
 * a single `engine-event` Tauri event as a tagged union.
 *
 * [`Status`](EngineEvent::Status) reports the engine's liveness transitions
 * (live ↔ last-good ↔ stopped); [`Error`](EngineEvent::Error) reports a structured
 * render/compile failure. Kept as ONE event type (tagged by `kind`) so the
 * frontend registers a single listener and the wire shape is fixed.
 */
export type EngineEvent = { "kind": "status", 
/**
 * The new engine status.
 */
status: EngineStatus, } | { "kind": "error", 
/**
 * The error payload.
 */
error: EngineErrorEvent, };
