// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A typed error from exporting a RetroArch `.slangp` bundle (the `export_preset`
 * command, #36, Fix C1). The webview-facing mirror of `preset_io::ExportError`:
 * it lives in `core-model` so a TypeScript binding is generated (module doc §A),
 * and — like [`ProjectSaveError`] / [`ProjectLoadError`] — it keeps the
 * semantically distinct failure modes as **branchable** variants instead of
 * collapsing them into one opaque string.
 *
 * `std::io::Error` is not `Clone`/`Eq`/`Serialize`, so the [`Io`] variant carries
 * only a message string rather than leaking the OS error directly, keeping the
 * whole enum a clean, serializable IPC payload the Phase-7 export UX can match on.
 *
 * [`Io`]: ExportError::Io
 */
export type ExportError = { "kind": "io", 
/**
 * The underlying I/O error message.
 */
message: string, } | { "kind": "graphPassUnsupported", 
/**
 * The id of the graph pass that cannot be exported yet.
 */
passId: string, };
