// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the `export_preset` command wrote, returned to the webview (#36, Fix C1):
 * where the bundle landed and what files it contains, plus any non-fatal notes.
 *
 * This is the success payload of the `export_preset` IPC command. It lives in
 * `core-model` — not in the `app` crate — so a TypeScript binding is generated
 * from the single shared schema (module doc §A) rather than escaping it as an
 * untyped, binding-less JSON shape. The richer [`preset_io::ExportReport`] is the
 * crate-internal writer report; this is its flattened, IPC-friendly projection
 * (absolute `presetPath` as a string, no `PathBuf`).
 */
export type ExportResult = { 
/**
 * Absolute path of the written `preset.slangp`.
 */
presetPath: string, 
/**
 * Per-pass `.slang` file names written, relative to the bundle root.
 */
passFiles: Array<string>, 
/**
 * LUT file names written under `textures/`, relative to the bundle root.
 */
textureFiles: Array<string>, 
/**
 * Non-fatal notes (e.g. a LUT source image that could not be copied in).
 */
warnings: Array<string>, };
