// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One structured reason a [`Project`] cannot be exported as-is (#64). The
 * pre-export validation gate ([`preset_io::validate_for_export`]) returns a list
 * of these; the export UX refuses to invoke the bundle writer while any are
 * present and lists them as the blocking reasons. Each variant carries enough
 * context for the UI to name the offending pass and (where possible) link into
 * the Problems panel.
 *
 * This is intentionally a SUPERSET of [`ExportError`]: `ExportError` is what the
 * writer reports if it is somehow invoked anyway (a defense-in-depth surface),
 * whereas an `ExportBlocker` is what the gate reports BEFORE the writer is asked
 * to do anything — the fail-closed contract (Spec §8 item 4: an invalid graph is
 * never silently exported).
 */
export type ExportBlocker = { "kind": "noPasses" } | { "kind": "uncompiledGraphPass", 
/**
 * The id of the graph pass that has no exportable slang.
 */
passId: string, 
/**
 * The pass's display name (for the blocking-reason list).
 */
passName: string, } | { "kind": "emptyPassSource", 
/**
 * The id of the pass with no source body.
 */
passId: string, 
/**
 * The pass's display name.
 */
passName: string, };
