// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExportBlocker } from "./ExportBlocker";

/**
 * The result of the pre-export validation gate (#64): the structured blockers (if
 * any) that prevent exporting a [`Project`] as a RetroArch bundle. `ok()` is the
 * fail-closed verdict the export UX checks before invoking the writer.
 */
export type ExportValidation = { 
/**
 * Every reason the project cannot be exported as-is. Empty ⇒ exportable.
 */
blockers: Array<ExportBlocker>, };
