// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortType } from "./PortType";

/**
 * The intrinsic operation an [`NodeOp::Expr`] performs over its operand ports
 * (Spec §8.3 node taxonomy). The set is deliberately the intrinsics #44's
 * fixtures exercise (color transform, contrast/gamma, UV warp, blur taps) plus
 * the common GLSL math the node taxonomy needs — each maps 1:1 to a slang
 * intrinsic or operator the emitter (#42) writes, and each is buildable by #44.
 *
 * **Arity / typing** (used by the #40 type checker): the binary arithmetic ops
 * are component-wise with scalar broadcast; `mix`/`clamp` are ternary; the unary
 * math ops are one operand; `dot` is binary → `float`; `normalize`/`length` act
 * on a vector; `swizzle` carries the selecting [`mask`](ExprOp::Swizzle::mask).
 */
export type ExprOp = { "op": "add" } | { "op": "sub" } | { "op": "mul" } | { "op": "div" } | { "op": "mix" } | { "op": "clamp" } | { "op": "min" } | { "op": "max" } | { "op": "pow" } | { "op": "sin" } | { "op": "cos" } | { "op": "abs" } | { "op": "floor" } | { "op": "fract" } | { "op": "dot" } | { "op": "normalize" } | { "op": "length" } | { "op": "swizzle", 
/**
 * The swizzle accessor mask (`xyzw` / `rgba` / `stpq`, length 1..=4).
 */
mask: string, } | { "op": "construct", 
/**
 * The vector type to construct.
 */
ty: PortType, };
