// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Edge } from "./Edge";
import type { Node } from "./Node";

/**
 * A per-pass node graph — a typed dataflow DAG (Architecture §C). Skeletal
 * here; the node taxonomy and typed ports arrive with the editor in Phase 5.
 */
export type Graph = { 
/**
 * The nodes in this graph.
 */
nodes: Array<Node>, 
/**
 * The directed, port-to-port connections between nodes.
 */
edges: Array<Edge>, };
