// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortRef } from "./PortRef";

/**
 * A directed, port-to-port connection in an [`IrGraph`] (Architecture §C): the
 * `source` node's **output** port feeds the `target` node's **input** port. The
 * value's type must be [`assignable_to`](PortType::assignable_to) the target
 * port's type (validated by the #40 type checker).
 */
export type IrEdge = { 
/**
 * The output port the value comes from.
 */
source: PortRef, 
/**
 * The input port the value flows into.
 */
target: PortRef, };
