// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IrEdge } from "./IrEdge";
import type { IrNode } from "./IrNode";

/**
 * The per-pass **typed dataflow DAG** (Architecture §C) — the codegen-facing
 * model the type checker (#40), lowering (#41), and emitter (#42) consume.
 *
 * This is the typed counterpart to the skeletal editor [`Graph`](crate::Graph)
 * (see the module docs): nodes are concrete [`NodeOp`]s with typed ports, edges
 * wire output ports to input ports. A well-formed graph has exactly one
 * reachable [`NodeOp::Output`] sink; the lowering pass topologically sorts from
 * it. Hand-built in Rust for Phase-4 tests; the editor → IR bridge is Phase 5.
 */
export type IrGraph = { 
/**
 * The typed nodes.
 */
nodes: Array<IrNode>, 
/**
 * The directed, port-to-port connections between nodes.
 */
edges: Array<IrEdge>, };
