// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeOp } from "./NodeOp";

/**
 * A single typed node in an [`IrGraph`]: a stable `id` plus its [`NodeOp`].
 */
export type IrNode = { 
/**
 * Stable unique id, referenced by [`IrEdge`]/[`PortRef`] and diagnostics.
 */
id: string, 
/**
 * The operation this node performs.
 */
op: NodeOp, };
