// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryPayload } from "./LibraryPayload";

/**
 * A project-independent, reusable building block in the personal library
 * (Phase 6, #56) — either a single [`Node`] or a whole [`Subgraph`]. A project
 * records which library items it instantiated via lightweight [`LibraryRef`]s;
 * the item bodies live in the library store (#58), never inline in the project.
 */
export type LibraryItem = { 
/**
 * Stable unique id the library store assigns; what a [`LibraryRef::item_id`]
 * points at.
 */
id: string, 
/**
 * Human-readable name shown in the library panel.
 */
name: string, 
/**
 * An optional longer description, or `None` if unset.
 */
description: string | null, 
/**
 * Free-form tags for filtering/grouping in the library panel.
 */
tags: Array<string>, 
/**
 * The reusable payload — a single node or a subgraph.
 */
payload: LibraryPayload, };
