// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A typed error from the on-disk library store ([`save_item`] / [`list_items`] /
 * [`delete_item`] and the matching `*_library_node` Tauri commands, #58).
 *
 * Mirrors [`ProjectLoadError`](crate::ProjectLoadError): `std::io::Error` is not
 * `Clone`/`Eq`/`Serialize`, so the [`Io`](LibraryError::Io) variant flattens a
 * failure to its `ErrorKind` label + message, keeping the whole enum a clean,
 * serializable IPC payload the frontend can match on. Note [`list_items`] never
 * returns this for a single corrupt file — it skips and logs that and carries on.
 */
export type LibraryError = { "kind": "io", 
/**
 * The `std::io::ErrorKind` label (e.g. `"PermissionDenied"`). Named
 * `errorKind` to avoid colliding with the `"kind"` serde tag.
 */
errorKind: string, 
/**
 * The OS error message.
 */
message: string, } | { "kind": "malformed", 
/**
 * The underlying `serde_json` message.
 */
message: string, } | { "kind": "notFound", 
/**
 * The id that was not found.
 */
id: string, };
