// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A reference from a project to a personal-library item it instantiated (Spec
 * §6: "project file holds library refs"; #38). This is a lightweight **pointer**
 * — the project records *which* library items it used, never the item bodies.
 *
 * The full `LibraryItem` schema and the on-disk library store arrive in Phase 6
 * (#56/#58); this fixes only the reference shape so the native project file can
 * already round-trip the refs. Resolving a ref to a concrete library item (and
 * handling a missing/updated item) is a Phase-6 concern.
 */
export type LibraryRef = { 
/**
 * The stable id of the referenced `LibraryItem` (Phase 6). Matches the id the
 * library store assigns; lets the editor mark instantiated regions and the
 * library panel show "used by N projects".
 */
itemId: string, 
/**
 * The library item's display name at the time it was instantiated, for
 * showing a meaningful label even when the item is no longer in the library.
 * `None` if not captured.
 */
name: string | null, };
