// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Node } from "./Node";
import type { Subgraph } from "./Subgraph";

/**
 * The reusable body of a [`LibraryItem`] — the "single node vs subgraph" kind
 * from the issue, expressed as the tagged-union discriminant (Phase 6, #56).
 */
export type LibraryPayload = { "kind": "node", 
/**
 * The library node.
 */
node: Node, } | { "kind": "subgraph", 
/**
 * The library subgraph.
 */
subgraph: Subgraph, };
