// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WrapMode } from "./WrapMode";

/**
 * An imported LUT texture (the `.slangp` `textures` family,
 * `docs/retroarch-slang-runtime.md` §7). A LUT is a static image loaded once and
 * bindable from any pass by its [`Lut::name`] (`<NAME>` / `<NAME>Size`). Carries
 * the per-texture sampler settings RetroArch reads from the `<NAME>_*` keys.
 *
 * The `.slangp` per-texture keys are each optional: `None` means the preset did
 * not set the key, so the engine applies the RetroArch LUT default (filtering =
 * nearest, wrap = `clampToBorder`, no mipmaps) rather than this baking one in.
 */
export type Lut = { 
/**
 * The LUT name as listed in `textures = "A;B"` and bound as `<NAME>` from a
 * pass body (§7). Unique within a project.
 */
name: string, 
/**
 * The image path, **already resolved** against the preset directory at import
 * time (#35) — an absolute path, or a normalized relative path that may point
 * outside the preset dir (e.g. `../shared/foo.png`). Stored as a string (the
 * model is the serde/TS contract; the parser uses `PathBuf` internally).
 */
path: string, 
/**
 * `<NAME>_linear` — `true`=linear, `false`=nearest filtering; `None` ⇒ the
 * preset did not set it (engine default: nearest, §7).
 */
filterLinear: boolean | null, 
/**
 * `<NAME>_wrap_mode` — sampler wrap for the LUT; `None` ⇒ unset (engine
 * default `clampToBorder`).
 */
wrapMode: WrapMode | null, 
/**
 * `<NAME>_mipmap` — generate a mip chain for the LUT; `None` ⇒ unset
 * (engine default: no mipmaps).
 */
mipmap: boolean | null, };
