// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuiltinSemantic } from "./BuiltinSemantic";
import type { ConstValue } from "./ConstValue";
import type { ExprOp } from "./ExprOp";
import type { PortDecl } from "./PortDecl";
import type { TextureSource } from "./TextureSource";

/**
 * The operation a single [`IrNode`] performs — the per-node op model
 * (Architecture §C). A node's **inputs** are wired by [`IrEdge`]s targeting its
 * input port names; its **output(s)** are referenced by edges sourcing its
 * output port names. The op carries only its intrinsic configuration (which
 * texture, which semantic, which literal, which intrinsic, the snippet body) —
 * never the wiring, which lives on the edges.
 *
 * ## Port-name conventions
 *
 * Each variant has a fixed set of port names the lowering pass (#41) and type
 * checker (#40) agree on:
 *
 * - [`Sample`](NodeOp::Sample): input `"coord"` (a `vec2`); output `"out"` (a `vec4`).
 * - [`Builtin`](NodeOp::Builtin): no inputs; output `"out"` (the semantic's type).
 * - [`Param`](NodeOp::Param): no inputs; output `"out"` (`float`).
 * - [`Const`](NodeOp::Const): no inputs; output `"out"` (the literal's type).
 * - [`Expr`](NodeOp::Expr): inputs are the entries of `operands` (in order);
 *   output `"out"`.
 * - [`Output`](NodeOp::Output): input `"color"` (a `vec4`); no output. Exactly
 *   one reachable [`Output`] per graph (the final color sink).
 * - [`CustomSnippet`](NodeOp::CustomSnippet): inputs/outputs are the declared
 *   [`PortDecl`]s, addressed by their `name`.
 */
export type NodeOp = { "kind": "sample", 
/**
 * Which RetroArch texture to sample.
 */
texture: TextureSource, } | { "kind": "builtin", 
/**
 * Which reserved RetroArch semantic to read.
 */
semantic: BuiltinSemantic, } | { "kind": "param", 
/**
 * The parameter identifier (must match a declared [`Parameter`](crate::Parameter)).
 */
name: string, } | { "kind": "const", 
/**
 * The literal value (and its type).
 */
value: ConstValue, } | { "kind": "expr", 
/**
 * The intrinsic to apply.
 */
op: ExprOp, 
/**
 * The **ordered** input port names this expression consumes. Each name
 * is an input port of this node that an [`IrEdge`] wires a value into;
 * the order is the operand order of `op` (e.g. `["a", "b"]` for `add`,
 * `["x", "lo", "hi"]` for `clamp`).
 */
operands: Array<string>, } | { "kind": "output" } | { "kind": "customSnippet", 
/**
 * The GLSL statements. References its input port names as in-scope
 * values and assigns its output port names.
 */
body: string, 
/**
 * Typed input ports (the snippet's free variables).
 */
inputs: Array<PortDecl>, 
/**
 * Typed output ports (the values the snippet assigns).
 */
outputs: Array<PortDecl>, };
