// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Vec2 } from "./Vec2";

/**
 * A single node in a per-pass [`Graph`].
 */
export type Node = { 
/**
 * Stable unique id (referenced by [`Edge`]s and diagnostics).
 */
id: string, 
/**
 * Node type key, e.g. `"sampler.source"`, `"math.mix"`, `"output"`. The
 * full taxonomy is defined in Phase 5 (Spec §8.3).
 */
kind: string, 
/**
 * Position on the editor canvas.
 */
position: Vec2, 
/**
 * Node configuration. Free-form JSON object until the typed node set lands;
 * the generated TypeScript types this as `Record<string, unknown>`. Defaults
 * to `{}` (not `null`) when omitted, so the on-wire value always matches the
 * non-nullable generated type.
 */
data: Record<string, unknown>, };
