// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A `#pragma parameter` declaration — a runtime knob shown as a slider (Spec §4).
 */
export type Parameter = { 
/**
 * Identifier used in the shader (the `#pragma parameter` name).
 */
name: string, 
/**
 * Human-readable label shown in the slider UI.
 */
label: string, 
/**
 * Default value.
 */
default: number, 
/**
 * Minimum slider value.
 */
min: number, 
/**
 * Maximum slider value.
 */
max: number, 
/**
 * Slider increment.
 */
step: number, };
