// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScaleAxis } from "./ScaleAxis";
import type { WrapMode } from "./WrapMode";

/**
 * RetroArch per-pass render settings carried on a [`Pass`]
 * (`docs/retroarch-slang-runtime.md` §1–§3). Every field is optional: `None`
 * means "the preset did not set this key" so the engine can apply the
 * position-dependent §2/§3 defaults rather than this baking one in.
 *
 * ## Combined-vs-per-axis scale precedence (§2)
 *
 * The `.slangp` file may set scale either combined (`scale_typeN` / `scaleN`,
 * applying to both axes) or per-axis (`scale_type_xN` / `scale_xN` and the `_y`
 * forms). Per [`preset_io::Pass::scale_type_x`] et al., the per-axis key wins
 * over the combined key for its axis, and a combined key applies to whichever
 * axis has no per-axis override. The import bridge ([`preset_io::import_preset`])
 * **resolves** that precedence and stores the already-effective per-axis values
 * in [`ScaleAxis`], so this model never carries the raw combined/per-axis
 * ambiguity — `scale_x`/`scale_y` here are the final values.
 */
export type PassSettings = { 
/**
 * Effective X-axis scale (combined/per-axis precedence already resolved).
 */
scaleX: ScaleAxis, 
/**
 * Effective Y-axis scale (combined/per-axis precedence already resolved).
 */
scaleY: ScaleAxis, 
/**
 * `filter_linearN` — `true`=linear, `false`=nearest input filtering; `None`
 * ⇒ unspecified (engine uses the §3 v1 default, linear).
 */
filterLinear: boolean | null, 
/**
 * `wrap_modeN` — sampler wrap for this pass's input; `None` ⇒ §3 default
 * (`clampToBorder`).
 */
wrapMode: WrapMode | null, 
/**
 * `mipmap_inputN` — generate a mip chain for this pass's input texture.
 */
mipmapInput: boolean | null, 
/**
 * `float_framebufferN` — `true` → RGBA16F render target (§3).
 */
floatFramebuffer: boolean | null, 
/**
 * `srgb_framebufferN` — `true` → RGBA8 sRGB render target (§3).
 */
srgbFramebuffer: boolean | null, 
/**
 * `aliasN` — semantic name enabling `<alias>` / `<alias>Size` /
 * `<alias>Feedback` bindings from later passes (§1/§4). Empty in the preset
 * ⇒ `None`.
 */
alias: string | null, 
/**
 * `frame_count_modN` — if `>0`, the `FrameCount` fed to this pass wraps mod
 * this value (§1). `None`/`0` ⇒ no wrap.
 */
frameCountMod: number | null, };
