// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Parameter } from "./Parameter";
import type { PassSource } from "./PassSource";

/**
 * One render pass — exactly one fragment shader (Spec §3). A pass is authored
 * either as a node [`Graph`] or supplied as opaque whole-pass code (e.g. from
 * preset import).
 */
export type Pass = { 
/**
 * Stable unique id (used by the pipeline view and to map diagnostics back).
 */
id: string, 
/**
 * Display name / alias for the pass.
 */
name: string, 
/**
 * What produces this pass's fragment shader.
 */
source: PassSource, 
/**
 * `#pragma parameter` knobs this pass exposes as live sliders (Spec §4).
 */
parameters: Array<Parameter>, };
