// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The set of RetroArch textures a single pass may bind, recorded as pipeline
 * metadata (#34). Causal: only earlier passes' outputs/aliases appear (plus the
 * always-available `Original`/`Source`, all LUTs, and any pass's feedback).
 */
export type PassAvailability = { 
/**
 * Index of the pass this availability is for, into [`Project::passes`].
 */
passIndex: number, 
/**
 * The semantic texture names bindable from this pass, in a deterministic
 * order (built-ins, then earlier `PassOutputK`, then earlier aliases, then
 * LUTs). Names only — sizes (`…Size`) and feedback twins are implied.
 */
available: Array<string>, };
