// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Graph } from "./Graph";

/**
 * How a pass's shader is defined (Spec §3, Architecture §C).
 */
export type PassSource = { "kind": "graph", 
/**
 * The per-pass node graph.
 */
graph: Graph, } | { "kind": "wholePassCode", 
/**
 * The complete `.slang` pass source.
 */
source: string, };
