// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AliasBinding } from "./AliasBinding";
import type { PassAvailability } from "./PassAvailability";

/**
 * Derived pipeline wiring metadata, reconstructed at import time (#34). This is
 * **metadata about** the rendered chain — ordering, alias bindings, and the
 * per-pass set of bindable RetroArch textures — and is deliberately **not** a
 * node-IR: whole-pass bodies are never decomposed (Architecture §C). It lets a
 * pass be referenced by its `#pragma name` / `aliasN` alias and lets the editor
 * surface what each pass may legally bind without re-scanning sources.
 */
export type PipelineMetadata = { 
/**
 * `alias` → pass index, for every pass that declares an `aliasN`
 * (`#pragma name`) (§1/§7). Lets a later pass's `<alias>` / `<alias>Feedback`
 * reference resolve to a concrete pass. Ordered by pass index.
 */
aliases: Array<AliasBinding>, 
/**
 * Per-pass availability: for each pass, the set of RetroArch texture
 * semantic names it may bind (`Original`, `Source`, `PassOutput0..i-1`,
 * earlier aliases, all LUTs, any feedback). Recorded as metadata so the
 * editor needn't re-derive causality. Indexed parallel to [`Project::passes`].
 */
availability: Array<PassAvailability>, };
