// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PixelFormat } from "./PixelFormat";

/**
 * The result of inspecting one preview pixel (#61).
 *
 * Always returned (the inspector never errors on an out-of-bounds hover): when the
 * pane coordinate falls in a letterbox bar, `inside` is `false` and `rgba` is the
 * bar color (black) — the frontend reports "outside" rather than a bogus sample.
 */
export type PixelSample = { 
/**
 * Whether the pane coordinate maps to a real content pixel (`true`) or landed
 * in a letterbox/pillarbox bar outside the content rect (`false`).
 */
inside: boolean, 
/**
 * The SIMULATED-VIEWPORT pixel X the pane coordinate maps to (content-rect
 * space; `0` when `inside` is false). NOT a raw pane pixel.
 */
x: number, 
/**
 * The SIMULATED-VIEWPORT pixel Y the pane coordinate maps to.
 */
y: number, 
/**
 * The simulated-viewport width the coordinate is reported against (the §9
 * content-rect width — the resolution the final image actually occupies).
 */
viewportWidth: number, 
/**
 * The simulated-viewport height the coordinate is reported against.
 */
viewportHeight: number, 
/**
 * The pixel's RGBA **as stored in the offscreen target**, normalized to `0..1`
 * (a byte/255 for the current `Rgba8Unorm` target). The pre-downsample value;
 * the frontend applies any sRGB/linear and 0-255/0-1 display conversion.
 */
rgba: [number, number, number, number], 
/**
 * The offscreen target's pixel format (today always `Rgba8Unorm`).
 */
format: PixelFormat, };
