// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The offscreen target's pixel format, reported alongside a [`PixelSample`] so the
 * frontend can label the readback (#61). Today the target is always
 * [`Rgba8Unorm`](PixelFormat::Rgba8Unorm); the float/srgb variants are the
 * documented hook for when higher-precision targets are wired (Spec §8.5) so the
 * inspector reports HDR/extended values rather than faking them.
 */
export type PixelFormat = "rgba8Unorm" | "rgba8UnormSrgb" | "rgba16Float";
