// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The direction of a [`BoundaryPort`] relative to the collapsed subgraph node
 * (Phase 6, #56). Serializes camelCase to `"in"` / `"out"`.
 */
export type PortDirection = "in" | "out";
