// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortType } from "./PortType";

/**
 * A typed input/output port declaration on a [`NodeOp::CustomSnippet`]
 * (Architecture §C). The snippet's GLSL `body` reads its declared `inputs` and
 * writes its declared `outputs` by name; the type checker validates the wired
 * edges against these types and the emitter substitutes them into the body.
 */
export type PortDecl = { 
/**
 * The port identifier (the GLSL variable name the snippet body uses).
 */
name: string, 
/**
 * The port's type.
 */
type: PortType, };
