// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A reference to one **port** on a node in an [`IrGraph`] — the endpoint an
 * [`IrEdge`] connects (Architecture §C). Ports are named by string identifiers
 * declared by the node's [`NodeOp`] (its input/output port names); an edge wires
 * a `(source.node, source.port)` output to a `(target.node, target.port)` input.
 */
export type PortRef = { 
/**
 * The [`IrNode::id`] this port belongs to.
 */
node: string, 
/**
 * The port identifier on that node (e.g. `"out"`, `"coord"`, `"a"`).
 */
port: string, };
