// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The type of a value flowing along a port edge in an [`IrGraph`] (Spec §8.2).
 *
 * These are the GLSL-ish scalar/vector/opaque types the node taxonomy traffics
 * in. The type checker (#40) uses the pure predicates below
 * ([`component_count`](PortType::component_count),
 * [`broadcast_to`](PortType::broadcast_to),
 * [`implicit_widen_to`](PortType::implicit_widen_to),
 * [`swizzle_result`](PortType::swizzle_result)) to validate edges and operator
 * operands; the emitter (#42) maps each to its slang spelling.
 */
export type PortType = "float" | "vec2" | "vec3" | "vec4" | "int" | "bool" | "sampler2D";
