// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A typed error from saving a native project file ([`Project::save_to_file`] and
 * the `save_project` Tauri command, #38). Serializing a well-formed [`Project`]
 * effectively never fails, so in practice this is an [`Io`] write error; both
 * variants exist so the command never panics and the frontend can match.
 *
 * [`Io`]: ProjectSaveError::Io
 */
export type ProjectSaveError = { "kind": "io", 
/**
 * The `std::io::ErrorKind` label (e.g. `"PermissionDenied"`). Named
 * `errorKind` to avoid colliding with the `"kind"` serde tag.
 */
errorKind: string, 
/**
 * The OS error message.
 */
message: string, } | { "kind": "serialize", 
/**
 * The underlying `serde_json` message.
 */
message: string, };
