// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A typed error from loading a native project file ([`Project::from_json`], and
 * the `load_project` Tauri command, #38). Returned instead of panicking on a
 * malformed or out-of-date file (Spec §6 acceptance).
 *
 * This carries no `std::io` variant: file IO is the caller's concern (the Tauri
 * command maps a read error separately). These variants describe only the
 * *content* of a project document.
 */
export type ProjectLoadError = { "kind": "malformed", 
/**
 * The underlying parser message.
 */
message: string, } | { "kind": "tooNew", 
/**
 * The version found in the file.
 */
found: number, 
/**
 * The newest version this build can read ([`PROJECT_SCHEMA_VERSION`]).
 */
supported: number, } | { "kind": "unsupported", 
/**
 * The version found in the file.
 */
found: number, 
/**
 * The current schema version ([`PROJECT_SCHEMA_VERSION`]).
 */
supported: number, };
