// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Lut } from "./Lut";
import type { Parameter } from "./Parameter";
import type { Pass } from "./Pass";
import type { PipelineMetadata } from "./PipelineMetadata";

/**
 * A ShaderBuilder project — the native project file (Spec §6). Distinct from an
 * exported `.slangp` bundle; this is the editable document the frontend owns
 * (Architecture §A).
 */
export type Project = { 
/**
 * Schema version of this project file; see [`PROJECT_SCHEMA_VERSION`].
 */
schemaVersion: number, 
/**
 * Human-readable project name.
 */
name: string, 
/**
 * The render pipeline: an ordered list of passes. Maps 1:1 to a `.slangp`
 * (Spec §3, pipeline view).
 */
passes: Array<Pass>, 
/**
 * `feedback_pass` — the global pass index double-buffered for feedback, or
 * `None` when the preset declares no global feedback pass (RetroArch default
 * `-1`). Distinct from per-pass `<alias>Feedback` bindings (§4). Carried on
 * the project so import → re-export is lossless.
 */
feedbackPass: number | null, 
/**
 * Derived pipeline wiring metadata (alias → pass index, per-pass texture
 * availability) reconstructed at import time (#34). This is *metadata about*
 * the chain — not a node-IR — so a pass can be referenced by its alias and
 * the editor knows which RetroArch textures each pass may bind. Defaults to
 * [`PipelineMetadata::default`] (empty) for hand-built projects.
 */
pipeline: PipelineMetadata, 
/**
 * The project's runtime parameter knobs — the **reconciled** set of
 * `#pragma parameter` declarations across every pass, with any `.slangp`
 * per-parameter overrides applied (#35). RetroArch parameters are global by
 * id: a parameter declared (identically) in several passes is **one** knob
 * here. This is the authoritative list the slider UI (#36 export) reads.
 * Distinct from a [`Pass`]'s own `parameters` (the raw per-pass
 * declarations). Defaults to `[]` for hand-built projects.
 */
parameters: Array<Parameter>, 
/**
 * Imported LUT textures (the `.slangp` `textures` family, §7), with paths
 * already resolved relative to the preset directory and per-texture sampler
 * settings carried (#35). Empty for hand-built projects. Defaults to `[]`.
 */
luts: Array<Lut>, };
