// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryRef } from "./LibraryRef";
import type { Lut } from "./Lut";
import type { Parameter } from "./Parameter";
import type { Pass } from "./Pass";
import type { PipelineMetadata } from "./PipelineMetadata";
import type { ProjectMetadata } from "./ProjectMetadata";

/**
 * A ShaderBuilder project — the native project file (Spec §6). Distinct from an
 * exported `.slangp` bundle; this is the editable document the frontend owns
 * (Architecture §A).
 */
export type Project = { 
/**
 * Schema version of this project file; see [`PROJECT_SCHEMA_VERSION`].
 */
schemaVersion: number, 
/**
 * Human-readable project name.
 */
name: string, 
/**
 * The render pipeline: an ordered list of passes. Maps 1:1 to a `.slangp`
 * (Spec §3, pipeline view).
 */
passes: Array<Pass>, 
/**
 * `feedback_pass` — the global pass index double-buffered for feedback, or
 * `None` when the preset declares no global feedback pass (RetroArch default
 * `-1`). Distinct from per-pass `<alias>Feedback` bindings (§4). Carried on
 * the project so import → re-export is lossless.
 */
feedbackPass: number | null, 
/**
 * Derived pipeline wiring metadata (alias → pass index, per-pass texture
 * availability) reconstructed at import time (#34). This is *metadata about*
 * the chain — not a node-IR — so a pass can be referenced by its alias and
 * the editor knows which RetroArch textures each pass may bind. Defaults to
 * [`PipelineMetadata::default`] (empty) for hand-built projects.
 */
pipeline: PipelineMetadata, 
/**
 * The project's runtime parameter knobs — the **reconciled** set of
 * `#pragma parameter` declarations across every pass, with any `.slangp`
 * per-parameter overrides applied (#35). RetroArch parameters are global by
 * id: a parameter declared (identically) in several passes is **one** knob
 * here. This is the authoritative list the slider UI (#36 export) reads.
 * Distinct from a [`Pass`]'s own `parameters` (the raw per-pass
 * declarations). Defaults to `[]` for hand-built projects.
 */
parameters: Array<Parameter>, 
/**
 * Imported LUT textures (the `.slangp` `textures` family, §7), with paths
 * already resolved relative to the preset directory and per-texture sampler
 * settings carried (#35). Empty for hand-built projects. Defaults to `[]`.
 */
luts: Array<Lut>, 
/**
 * Free-form authoring metadata for the native project file (Spec §6, #38):
 * description, author, timestamps. Every field is optional and the whole
 * struct defaults to empty, so older project files (and import-produced
 * projects) load with no metadata. This is **document** metadata; it is
 * deliberately separate from pipeline wiring (which lives in [`pipeline`]).
 *
 * [`pipeline`]: Project::pipeline
 */
metadata: ProjectMetadata, 
/**
 * References to personal-library items this project instantiated (Spec §6:
 * "project file holds library refs"; #38, forward-looking for the Phase-6
 * library, #56/#58). Each entry is a lightweight pointer (id + display name)
 * to a `LibraryItem` stored elsewhere — the project records *which* library
 * items it used, never the item bodies. Empty for projects that used no
 * library items. Defaults to `[]`.
 *
 * The full `LibraryItem` schema and the library store land in Phase 6; this
 * only fixes the reference shape so the native project file can already carry
 * the refs without round-trip loss.
 */
libraryRefs: Array<LibraryRef>, };
