// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Pass } from "./Pass";

/**
 * A ShaderBuilder project — the native project file (Spec §6). Distinct from an
 * exported `.slangp` bundle; this is the editable document the frontend owns
 * (Architecture §A).
 */
export type Project = { 
/**
 * Schema version of this project file; see [`PROJECT_SCHEMA_VERSION`].
 */
schemaVersion: number, 
/**
 * Human-readable project name.
 */
name: string, 
/**
 * The render pipeline: an ordered list of passes. Maps 1:1 to a `.slangp`
 * (Spec §3, pipeline view).
 */
passes: Array<Pass>, };
