// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A typed error from loading a native project file ([`Project::from_json`] /
 * [`Project::load_from_file`], and the `load_project` Tauri command, #38).
 * Returned instead of panicking on a missing, malformed, or out-of-date file
 * (Spec §6 acceptance).
 *
 * `std::io::Error` is not `Clone`/`Eq`/`Serialize`, so the [`Io`] variant
 * flattens a read failure to its `ErrorKind` label + message; this keeps the
 * whole enum a clean, serializable IPC payload the Phase-7 UX can match on (e.g.
 * distinguishing "file not found" from "corrupt file"). The content-only
 * helper [`Project::from_json`] never produces [`Io`].
 *
 * [`Io`]: ProjectLoadError::Io
 */
export type ProjectLoadError = { "kind": "io", 
/**
 * The `std::io::ErrorKind` label (e.g. `"NotFound"`), for matching.
 * Named `errorKind` to avoid colliding with the `"kind"` serde tag.
 */
errorKind: string, 
/**
 * The OS error message.
 */
message: string, } | { "kind": "malformed", 
/**
 * The underlying parser message.
 */
message: string, } | { "kind": "tooNew", 
/**
 * The version found in the file.
 */
found: number, 
/**
 * The newest version this build can read ([`PROJECT_SCHEMA_VERSION`]).
 */
supported: number, } | { "kind": "unsupported", 
/**
 * The version found in the file.
 */
found: number, 
/**
 * The current schema version ([`PROJECT_SCHEMA_VERSION`]).
 */
supported: number, };
