// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Free-form authoring metadata for the native project file (Spec §6, #38).
 *
 * This is **document** metadata — human-facing description, authorship, and
 * timestamps — kept distinct from the render [`PipelineMetadata`] (which is
 * *wiring* metadata about the chain). Every field is optional so a project may
 * carry none of it, and the whole struct defaults to empty so older project
 * files and import-produced projects load unchanged.
 *
 * Timestamps are stored as **opaque strings** (RFC 3339 is the intended
 * convention) rather than a date type, so the serde/TS contract stays
 * dependency-free and the frontend owns formatting. The save/load commands do
 * not interpret or mutate these fields — they are authored by the UI.
 */
export type ProjectMetadata = { 
/**
 * A longer human-readable description of the project, or `None` if unset.
 */
description: string | null, 
/**
 * The author / creator name, or `None` if unset.
 */
author: string | null, 
/**
 * When the project was first created, as an opaque (RFC 3339) string, or
 * `None` if unset.
 */
createdAt: string | null, 
/**
 * When the project was last modified, as an opaque (RFC 3339) string, or
 * `None` if unset.
 */
modifiedAt: string | null, };
