// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry in the recent-projects list (#63): the absolute project-file path
 * plus the display name captured at the time it was opened/saved, so the File
 * menu can show a friendly label without re-reading every file.
 */
export type RecentProject = { 
/**
 * The absolute path to the `.json` project file.
 */
path: string, 
/**
 * The project's display name at open/save time (best-effort label).
 */
name: string, };
