// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Project } from "./Project";
import type { RecoveryMeta } from "./RecoveryMeta";

/**
 * A recovered autosave (#63): the working [`Project`] plus its [`RecoveryMeta`].
 */
export type Recovery = { 
/**
 * The recovered working document.
 */
project: Project, 
/**
 * When/where it was autosaved.
 */
meta: RecoveryMeta, };
