// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadata stamped alongside an autosave recovery document (#63).
 */
export type RecoveryMeta = { 
/**
 * The project-file path the recovered document came from, or `None` for a
 * never-saved (new, untitled) document.
 */
projectPath: string | null, 
/**
 * The project's display name at autosave time (for the restore prompt).
 */
name: string, 
/**
 * Milliseconds since the Unix epoch when the autosave was written.
 */
savedAtMs: bigint, };
