// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScaleType } from "./ScaleType";

/**
 * One axis of a pass's scale specification: a scale type and its factor
 * (`docs/retroarch-slang-runtime.md` §2). Each field is `Option` so an absent
 * preset key stays absent — the engine applies the position-dependent default
 * (intermediate = `source × 1.0`, final = `viewport`) rather than this carrying
 * an invented value.
 *
 * For `Absolute` the `scale` is the literal integer pixel count (stored as
 * `f32`; callers round). For `Source`/`Viewport` it multiplies the relevant
 * size.
 */
export type ScaleAxis = { 
/**
 * The effective scale type for this axis, or `None` if the preset set no
 * scale-type key for it.
 */
scaleType: ScaleType | null, 
/**
 * The effective scale factor for this axis, or `None` if the preset set no
 * scale-factor key for it.
 */
scale: number | null, };
