// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a pass's render target (FBO) size is derived from the available size
 * inputs (`docs/retroarch-slang-runtime.md` §2). The serde tag is the exact
 * RetroArch `.slangp` string, so import → export round-trips losslessly.
 *
 * The librashader-only `Original` extension has no upstream preset string and
 * is intentionally **not** represented here (§11 open-question 1).
 */
export type ScaleType = "source" | "viewport" | "absolute";
