// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A typed error from the session store (#63), mirroring
 * [`LibraryError`](crate::LibraryError): `std::io::Error` is not
 * `Clone`/`Eq`/`Serialize`, so [`Io`](SessionError::Io) flattens a failure to its
 * `ErrorKind` label + message, keeping the enum a clean, serializable IPC payload.
 */
export type SessionError = { "kind": "io", 
/**
 * The `std::io::ErrorKind` label (e.g. `"PermissionDenied"`).
 */
errorKind: string, 
/**
 * The OS error message.
 */
message: string, } | { "kind": "malformed", 
/**
 * The underlying `serde_json` message.
 */
message: string, };
