// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoundaryPort } from "./BoundaryPort";
import type { Edge } from "./Edge";
import type { Node } from "./Node";

/**
 * A named, collapsible group of nodes/edges with declared typed boundary ports
 * — the typed body of a **collapsed-subgraph node** and one of the two
 * [`LibraryPayload`] kinds (Phase 6, #56).
 *
 * ## How a subgraph lives in a [`Graph`]
 *
 * A collapsed subgraph is **not** a new graph variant: it is a perfectly
 * ordinary skeletal [`Node`] whose [`Node::kind`] is `"subgraph"` and whose
 * free-form [`Node::data`] (a `serde_json::Value`) holds **this** struct,
 * serialized. The Phase-5 architecture deliberately keeps `Node.kind: String`
 * and `Node.data: Record<string, unknown>` free-form and lets the TypeScript
 * descriptor registry interpret `kind`; `Subgraph` is simply the typed *shape*
 * of a `kind == "subgraph"` node's `data`. `Node`/`Graph` therefore stay plain
 * structs (never an enum), and a `Graph` can hold subgraph nodes and ordinary
 * nodes side by side and round-trip losslessly.
 *
 * ## Body
 *
 * The interior is held as the **same** skeletal [`Node`]/[`Edge`] types as any
 * graph, plus an ordered list of typed [`BoundaryPort`]s describing the ports
 * the collapsed node exposes to the exterior. Inlining/lowering a subgraph into
 * the typed IR happens later, in the TypeScript `graphToIr` bridge (#57) — *not*
 * in Rust. core-model only fixes the data shape and the instantiate contract;
 * it never touches the IR / checker / lower / emit.
 */
export type Subgraph = { 
/**
 * Stable unique id of this subgraph body. Distinct from the id of the
 * wrapping `kind == "subgraph"` [`Node`] that carries it (the wrapper node's
 * id is minted by the store when the node is placed on the canvas).
 */
id: string, 
/**
 * Human-readable name shown on the collapsed subgraph node and in the
 * library.
 */
name: string, 
/**
 * The interior nodes — ordinary skeletal [`Node`]s (Phase-5 shape).
 */
nodes: Array<Node>, 
/**
 * The interior, port-to-port [`Edge`]s between interior nodes.
 */
edges: Array<Edge>, 
/**
 * The ordered list of typed ports the collapsed subgraph node exposes to the
 * exterior, each mapping to one interior endpoint.
 */
boundaryPorts: Array<BoundaryPort>, };
