// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A concrete RetroArch texture a [`NodeOp::Sample`] reads from (Spec §7 binding
 * table). This is the **typed, resolved** reference (it carries its index/name),
 * distinct from the import-scan's coarse [`TextureRefKind`](crate::TextureRefKind)
 * classification: the emitter (#42) maps each variant to a concrete RetroArch
 * sampler identifier (`Source`, `Original`, `OriginalHistory2`, `PassOutput0`,
 * `PassFeedback1`, or a LUT name) and assigns its `layout(set=0, binding=N)`.
 *
 * History/PassOutput/PassFeedback carry a `u32` index; a LUT carries its name.
 */
export type TextureSource = { "kind": "source" } | { "kind": "original" } | { "kind": "originalHistory", 
/**
 * How many frames back (`OriginalHistory{index}`).
 */
index: number, } | { "kind": "passOutput", 
/**
 * The producing pass index (`PassOutput{index}`).
 */
index: number, } | { "kind": "passFeedback", 
/**
 * The producing pass index (`PassFeedback{index}`).
 */
index: number, } | { "kind": "lut", 
/**
 * The LUT name as declared in the project's `luts`.
 */
name: string, };
