// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextureRefKind } from "./TextureRefKind";

/**
 * One RetroArch texture/alias a whole-pass source textually references (§7),
 * found by the import-time scan (#34). This is *wiring metadata*, deliberately
 * shallow: it records the **name** as written and a coarse [`TextureRefKind`]
 * classification — it does not model where in the body the read occurs, nor
 * does it decompose the pass into node-IR.
 */
export type TextureRef = { 
/**
 * The texture/sampler identifier exactly as it appears in the source, e.g.
 * `"Original"`, `"Source"`, `"PassOutput2"`, `"MyAliasFeedback"`, or a LUT
 * name like `"BORDER"`.
 */
name: string, 
/**
 * Coarse classification of what `name` refers to (§7 binding table).
 */
kind: TextureRefKind, };
