// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Coarse classification of a [`TextureRef`] (§7 sampler binding table). The
 * import scan classifies by the well-known RetroArch prefixes; anything else is
 * [`TextureRefKind::Alias`] (a `#pragma name` pass alias or a LUT name —
 * resolved against the alias/LUT tables, not distinguished by the scan).
 */
export type TextureRefKind = "original" | "source" | "passOutput" | "feedback" | "history" | "user" | "alias";
