// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The simulated viewport the final pass renders into (#30, Architecture §D,
 * Spec §4, `docs/retroarch-slang-runtime.md` §2/§9): the output resolution
 * RetroArch would target, with an optional integer-scale toggle.
 *
 * This is the resolution `FinalViewportSize` reports and `viewport`-scaled FBOs
 * multiply — distinct from the preview *pane* size (the read-back/stream target).
 * The engine computes the effective content rectangle from this and the source
 * size (aspect-correct fit, or — when `integer_scale` is set — the largest
 * integer multiple of the source that fits), letterboxing the remainder. See
 * `preview_engine::viewport::ViewportConfig` for the canonical math.
 */
export type Viewport = { 
/**
 * Output resolution width in pixels.
 */
width: number, 
/**
 * Output resolution height in pixels.
 */
height: number, 
/**
 * When `true`, snap the content rectangle to the largest integer multiple
 * of the source size that fits the output resolution (letterboxing the
 * remainder). When `false`, aspect-correct fit preserving the source ratio.
 */
integerScale: boolean, };
