// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sampler wrap mode for a pass's (or LUT's) source texture
 * (`docs/retroarch-slang-runtime.md` §3, `video_shader_wrap_str_to_mode`). The
 * serde representation is camelCase (e.g. `"clampToBorder"`) per the §A
 * convention; the v1 default is [`WrapMode::ClampToBorder`].
 */
export type WrapMode = "clampToBorder" | "clampToEdge" | "repeat" | "mirroredRepeat";
