// The edit → compile → preview loop core (#54) — the integration seam that closes
// the live editing loop: per-pass `graphToIr` → `compile_graph` → diagnostics +
// generated slang → the engine preview.
//
// AUTHORITY: Rust stays authoritative for type-check / lower / emit / render. This
// module only orchestrates: it serializes each graph pass to the FROZEN `IrGraph`
// (the bridge, #49), asks `compile_graph` per pass (the Phase-4 pipeline, #42),
// then maps the returned diagnostics back to the offending editor node ids and
// hands the generated slang chain to the engine (`load_shader_source` /
// `load_chain_sources`, the in-memory live-preview commands #54 added in Rust).
//
// PER-PASS (Architecture / GOTCHA): `compile_graph` is per pass. A graph pass is
// lowered + compiled; a WHOLE-PASS code pass is opaque — its verbatim source is the
// pass source as-is (no IrGraph, no compile_graph). Diagnostics aggregate across all
// passes, keyed by node id; the chain feeds ALL passes' sources to the engine in
// pipeline order.
//
// PURITY: `compileProject` takes an injected `invokeCompile` so the whole loop is
// unit-testable with no Tauri runtime (the hook passes the real `invoke`).
import type { CompileGraphResult } from "../bindings/CompileGraphResult";
import type { Diagnostic } from "../bindings/Diagnostic";
import type { IrGraph } from "../bindings/IrGraph";
import type { Parameter } from "../bindings/Parameter";
import type { Pass } from "../bindings/Pass";
import type { PassSettings } from "../bindings/PassSettings";
import type { Project } from "../bindings/Project";
import { graphToIr, type GraphToIrIssue } from "../nodes/graphToIr";

/** A single pass's compile inputs, derived from the document (pure). */
export interface PassPlan {
  /** The pass id (so diagnostics + chain order trace back to the document). */
  passId: string;
  /** The pass alias / `#pragma name` (for the emitted `#pragma name`). */
  name: string | null;
  /** The pass's render settings (drives the live-preview chain's scale/format). */
  settings: PassSettings;
  /**
   * For a GRAPH pass: the typed IrGraph to compile + its derived parameters/LUTs/
   * graphToIr issues. `null` for a whole-pass code pass (which is opaque).
   */
  graph: {
    ir: IrGraph;
    parameters: Parameter[];
    luts: string[];
    issues: GraphToIrIssue[];
  } | null;
  /**
   * For a WHOLE-PASS code pass: its verbatim source (used as-is, never lowered).
   * `null` for a graph pass (whose source is generated by `compile_graph`).
   */
  wholePassSource: string | null;
}

/** Build the per-pass compile plan for a project (pure — no IPC). */
export function planProject(project: Project): PassPlan[] {
  return project.passes.map((pass) => planPass(pass, project));
}

/** Build one pass's compile plan (pure). */
function planPass(pass: Pass, project: Project): PassPlan {
  const name = pass.settings.alias && pass.settings.alias.length > 0 ? pass.settings.alias : null;
  if (pass.source.kind === "graph") {
    const { ir, parameters, luts, issues } = graphToIr(pass.source.graph);
    // The pass declares parameters/LUTs from its Param/LUT nodes (graphToIr) AND
    // its own authored lists + the project-level declarations; merge so the
    // checker's context covers every name the graph references.
    const mergedParams = mergeParameters(parameters, pass.parameters, project.parameters);
    const mergedLuts = mergeLuts(luts, project.luts.map((l) => l.name));
    return {
      passId: pass.id,
      name,
      settings: pass.settings,
      graph: { ir, parameters: mergedParams, luts: mergedLuts, issues },
      wholePassSource: null,
    };
  }
  return {
    passId: pass.id,
    name,
    settings: pass.settings,
    graph: null,
    wholePassSource: pass.source.source,
  };
}

/** De-duplicate parameters by name (first wins), across the given lists in order. */
function mergeParameters(...lists: Parameter[][]): Parameter[] {
  const out: Parameter[] = [];
  const seen = new Set<string>();
  for (const list of lists) {
    for (const p of list) {
      if (!seen.has(p.name)) {
        seen.add(p.name);
        out.push(p);
      }
    }
  }
  return out;
}

/** De-duplicate LUT names (first wins), across the given lists in order. */
function mergeLuts(...lists: string[][]): string[] {
  const out: string[] = [];
  const seen = new Set<string>();
  for (const list of lists) {
    for (const name of list) {
      if (!seen.has(name)) {
        seen.add(name);
        out.push(name);
      }
    }
  }
  return out;
}

/** One pass's result after compiling: its generated source + per-pass diagnostics. */
export interface PassCompileResult {
  passId: string;
  /** Generated slang for the live preview, or `null` when the pass is unrenderable. */
  source: string | null;
  settings: PassSettings;
  /** The diagnostics this pass produced (mapped to node ids by `node`). */
  diagnostics: Diagnostic[];
}

/** One aggregate problems-list row: a diagnostic tagged with its origin pass. */
export interface ProblemEntry {
  passId: string;
  passName: string;
  diagnostic: Diagnostic;
}

/** The whole project's compile outcome — what the hook pushes to the store + engine. */
export interface ProjectCompileResult {
  /** Per-pass results in pipeline order. */
  passes: PassCompileResult[];
  /**
   * Diagnostics keyed by the offending editor node id (the store's
   * `diagnosticsByNode`, which the inspector + node badges read). A node with no
   * problems is absent.
   */
  diagnosticsByNode: Record<string, Diagnostic[]>;
  /** The flat aggregate problems list, in pipeline order (pass-tagged). */
  problems: ProblemEntry[];
  /**
   * Whether the WHOLE pipeline is renderable: every pass produced a non-null
   * source. A single unrenderable pass (cycle / type error / lowering failure)
   * makes the pipeline globally invalid so the editor can flag it.
   */
  valid: boolean;
}

/** The injected `compile_graph` caller (the hook passes the real Tauri `invoke`). */
export type InvokeCompile = (args: {
  graph: IrGraph;
  parameters: Parameter[];
  luts: string[];
  name: string | null;
  format: string | null;
}) => Promise<CompileGraphResult>;

/**
 * Compile every pass of a project (pure orchestration over the injected
 * `compile_graph` caller). A graph pass is type-checked + emitted by Rust; a
 * whole-pass code pass is opaque — its verbatim source is used and it contributes
 * no IR diagnostics. The result aggregates diagnostics by node id and reports
 * whether the whole pipeline is renderable.
 */
export async function compileProject(
  project: Project,
  invokeCompile: InvokeCompile,
): Promise<ProjectCompileResult> {
  const plans = planProject(project);
  const passNames = new Map(project.passes.map((p) => [p.id, p.name] as const));
  const passes: PassCompileResult[] = [];
  const diagnosticsByNode: Record<string, Diagnostic[]> = {};
  const problems: ProblemEntry[] = [];

  const pushDiag = (passId: string, d: Diagnostic): void => {
    const list = diagnosticsByNode[d.node] ?? (diagnosticsByNode[d.node] = []);
    list.push(d);
    problems.push({ passId, passName: passNames.get(passId) ?? passId, diagnostic: d });
  };

  for (const plan of plans) {
    if (plan.wholePassSource !== null) {
      // Whole-pass code: opaque, taken verbatim. No IrGraph, no compile_graph.
      passes.push({
        passId: plan.passId,
        source: plan.wholePassSource,
        settings: plan.settings,
        diagnostics: [],
      });
      continue;
    }

    const g = plan.graph!;
    // graphToIr issues (a dropped/unknown node) surface as synthetic diagnostics
    // on the offending node id, so the editor flags them inline too.
    const passDiags: Diagnostic[] = g.issues.map(issueToDiagnostic);

    const result = await invokeCompile({
      graph: g.ir,
      parameters: g.parameters,
      luts: g.luts,
      name: plan.name,
      format: null,
    });
    for (const d of result.diagnostics.items) {
      passDiags.push(d);
    }
    for (const d of passDiags) {
      pushDiag(plan.passId, d);
    }
    passes.push({
      passId: plan.passId,
      source: result.source,
      settings: plan.settings,
      diagnostics: passDiags,
    });
  }

  const valid = passes.length > 0 && passes.every((p) => p.source !== null);
  return { passes, diagnosticsByNode, problems, valid };
}

/** Map a graphToIr lowering issue onto a node-keyed error diagnostic. */
function issueToDiagnostic(issue: GraphToIrIssue): Diagnostic {
  return {
    severity: "error",
    code: issue.reason === "unknownKind" ? "unknownKind" : "loweringError",
    message: issue.message,
    node: issue.nodeId,
    port: null,
  };
}
